import Head from "next/head";
import { Inter } from "next/font/google";

import Link from "next/link";
import { Heading, Text } from "@chakra-ui/react";
import Layout from "./layout";
import styled from "styled-components";

const List = styled.ul`
  padding: 4px 32px;
`;

const pageLinks = [
  { url: "/problems/addBinary", title: "Add Binary" },
  { url: "/problems/balancedBinaryTree", title: "Balanced Binary Tree" },
  { url: "/problems/binarySearch", title: "Binary Search" },
  {
    url: "/problems/binaryTreeLevelOrderTraversal",
    title: "Binary Tree Level Order Traversal",
  },
  { url: "/problems/climbingStairs", title: "Climbing Stairs" },
  { url: "/problems/cloneGraph", title: "Clone Graph" },
  { url: "/problems/coinChange", title: "Coin Change" },
  { url: "/problems/combinationSum", title: "Combination Sum" },
  { url: "/problems/containsDuplicate", title: "Contains Duplicate" },
  { url: "/problems/countingBits", title: "Counting Bits" },
  // { url: "/problems/x", title: "x" },
];

export default function Home() {
  return (
    <>
      <Head>
        <title>Leet Code Workbook</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Layout>
          <Heading fontSize="4xl" my="6">
            Completed Problems
          </Heading>
          <List>
            {pageLinks.map((item) => (
              <li key={item.url}>
                <Link href={item.url}>{item.title}</Link>
              </li>
            ))}
          </List>
        </Layout>
      </main>
    </>
  );
}
