import Head from "next/head";
import { Inter } from "next/font/google";

import Link from "next/link";
import { Text } from "@chakra-ui/react";
import Layout from "./layout";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Layout>
          <Text fontSize="4xl">Coooool</Text>
          <Link href="/problems/twoSum">TwoSum</Link>
        </Layout>
      </main>
    </>
  );
}
